"""add return date and late fee to bookings

Revision ID: 7ca37752a501
Revises: fb4ae1a7e903
Create Date: 2026-08-17 12:47:07.448321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca37752a501'
down_revision = 'fb4ae1a7e903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_return_date', sa.Date(), nullable=True))
        batch_op.add_column(
            sa.Column(
                'late_fee',
                sa.Numeric(precision=10, scale=2),
                nullable=False,
                server_default='0',
            )
        )

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('late_fee')
        batch_op.drop_column('actual_return_date')

    # ### end Alembic commands ###
