"""kenya mvp: phone, vehicle location/category, booking reference/driver/deposit, payment mock mpesa/refund, company settings

Revision ID: b6e0dd64c4ed
Revises: 4f7a2e9c1b8d
Create Date: 2026-08-20 14:59:31.113452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e0dd64c4ed'
down_revision = '4f7a2e9c1b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('with_driver', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('driver_rate', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_bookings_reference'), ['reference'], unique=True)

    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit_percentage', sa.Numeric(precision=5, scale=2), nullable=False, server_default='30.00'))
        batch_op.add_column(sa.Column('driver_daily_rate', sa.Numeric(precision=10, scale=2), nullable=False, server_default='2500.00'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('mpesa_receipt', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('refunded_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_vehicles_location'), ['location'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_location'))
        batch_op.drop_column('location')
        batch_op.drop_column('category')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_column('phone')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('refunded_at')
        batch_op.drop_column('mpesa_receipt')
        batch_op.drop_column('transaction_id')

    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.drop_column('driver_daily_rate')
        batch_op.drop_column('deposit_percentage')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_reference'))
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('driver_rate')
        batch_op.drop_column('with_driver')
        batch_op.drop_column('deposit_amount')
        batch_op.drop_column('reference')

    # ### end Alembic commands ###
